package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import java.io.IOException;
import javafx.event.ActionEvent;
import javafx.scene.control.ListView;
import java.util.List;

public class InventoryViewController {
	@FXML
	private Button deliveryUpdateButton;
	@FXML
	private ListView currentInventoryListView;
	@FXML
	private TextField deliveryDateField;
	@FXML
	private Button generateReportButton;
	@FXML
	private ListView incomingShipmentListView;

	// Event Listener on Button[#deliveryUpdateButton].onAction
	@FXML
	public void deliveryUpdateButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	
	private List<Order> orders;
    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

	// Event Listener on Button[#generateReportButton].onAction
	@FXML
	public void generateReportButtonClick(ActionEvent event) {
		Report report = new Report();
		report.popularReport(orders);
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/ReportView.fxml"));
		AnchorPane dialogRoot;
		//try except to get the new window to show
		try {
			dialogRoot = (AnchorPane) loader.load();
			Scene dialogScene = new Scene(dialogRoot);
			Stage dialogStage = new Stage();
			dialogStage.setScene(dialogScene);
			ReportViewController dialogController = (ReportViewController) loader.getController();
			dialogController.getMostPopularField().setText(report.getMostPopularThneed());
			dialogStage.show();
			System.out.println("After dialogStage.show()");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
